### ISSUE TITLE
Precondition failed when trying to spend multiple times using GA

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aeternity#3947]
## Expected Behavior

To don't have 412 response or have it documented in https://testnet.aeternity.io/api?oas3

## Actual Behavior

Node randomly responses with 412 code.

## Steps to Reproduce the Problem

Execute this script with `@aeternity/aepp-sdk@12` installed.
```js
import { Node, AeSdk, MemoryAccount, generateKeyPair, salt } from '@aeternity/aepp-sdk/es/index.mjs';

const account = new MemoryAccount({
  keypair: {
    publicKey: 'ak_2dATVcZ9KJU5a8hdsVtTv21pYiGWiPbmVcU1Pz72FFqpk9pSRR',
    secretKey: 'bf66e1c256931870908a649572ed0257876bb84e3cdf71efb12f56c7335fad54d5cf08400e988222f26eb4b02c8f89077457467211a6e6d955edb70749c6a33b'
  }
});
const sdk = new AeSdk({
  nodes: [{ name: 'testnet', instance: new Node('https://testnet.aeternity.io') }],
  compilerUrl: 'https://compiler.aepps.com',
});
const ga = new MemoryAccount({ keypair: generateKeyPair() });
await sdk.spend(1e16, await ga.address(), { onAccount: account });

const authContractSource = `contract BlindAuth =
  stateful entrypoint authorize(r: int) : bool =
    // r is a random number only used to make tx hashes unique
    switch(Auth.tx_hash)
      None          => abort("Not in Auth context")
      Some(tx_hash) => true
`;
await sdk.createGeneralizedAccount('authorize', authContractSource, [], { onAccount: ga });
await sdk.addAccount(new MemoryAccount({ gaId: await ga.address() }), { select: true });

const r = () => salt();
const { publicKey } = generateKeyPair();

for (let i = 0; i < 100; i++) {
  console.log(`spend ${i}`);
  await sdk.spend(10000, publicKey, { authData: { source: authContractSource, args: [r()] } });
}
```

## Configuration, logs, error output, etc.

```bash
$ node reproduction.mjs
spend 0
spend 1
spend 2
spend 3
spend 4
spend 5
spend 6
/.../node_modules/@azure/core-client/dist/index.js:1263
    const error = new coreRestPipeline.RestError(initialErrorMessage, {
                  ^

RestError
    at handleErrorResponse (/.../node_modules/@azure/core-client/dist/index.js:1263:19)
    at deserializeResponseBody (/.../node_modules/@azure/core-client/dist/index.js:1198:45)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: undefined,
  statusCode: 412,
  request: PipelineRequestImpl {
    url: 'https://testnet.aeternity.io/v3/transactions/th_aJMfDmZ5bQKCg3QW9YQqJCxqLkHjx5FgsFXKCWDsG3oqwehiu?int-as-string=true',
    body: undefined,
    headers: HttpHeadersImpl {
      _headersMap: Map(4) {
        'accept' => { name: 'Accept', value: 'application/json' },
        'accept-encoding' => { name: 'Accept-Encoding', value: 'gzip,deflate' },
        'user-agent' => {
          name: 'User-Agent',
          value: 'azsdk-js-node/1.0.0-beta.1 core-rest-pipeline/1.9.0 Node/v16.15.1 OS/(x64-Darwin-21.5.0)'
        },
        'x-ms-client-request-id' => {
          name: 'x-ms-client-request-id',
          value: 'bbe96b86-0e5b-4817-b0e9-ecca29f5502a'
        }
      }
    },
    method: 'GET',
    timeout: 0,
    formData: undefined,
    disableKeepAlive: false,
    proxySettings: undefined,
    streamResponseStatusCodes: Set(0) {},
    withCredentials: false,
    abortSignal: undefined,
    tracingOptions: undefined,
    onUploadProgress: undefined,
    onDownloadProgress: undefined,
    requestId: 'bbe96b86-0e5b-4817-b0e9-ecca29f5502a',
    allowInsecureConnection: true,
    enableBrowserStreams: false
  },
  response: {
    status: 412,
    headers: HttpHeadersImpl {
      _headersMap: Map(8) {
        'content-length' => { name: 'content-length', value: '0' },
        'connection' => { name: 'connection', value: 'keep-alive' },
        'date' => { name: 'date', value: 'Thu, 07 Jul 2022 07:45:16 GMT' },
        'server' => { name: 'server', value: 'Cowboy' },
        'x-cache' => { name: 'x-cache', value: 'Miss from cloudfront' },
        'via' => {
          name: 'via',
          value: '1.1 8556a7e6f097b43ef38a15da76d83874.cloudfront.net (CloudFront)'
        },
        'x-amz-cf-pop' => { name: 'x-amz-cf-pop', value: 'ARN1-C1' },
        'x-amz-cf-id' => {
          name: 'x-amz-cf-id',
          value: 'xEhw7c8i18jfybd0cRgQ2GLMxtN2rM6wzhjRM86qhlBRuR-xvHQyAA=='
        }
      }
    },
    request: PipelineRequestImpl {
      url: 'https://testnet.aeternity.io/v3/transactions/th_aJMfDmZ5bQKCg3QW9YQqJCxqLkHjx5FgsFXKCWDsG3oqwehiu?int-as-string=true',
      body: undefined,
      headers: HttpHeadersImpl {
        _headersMap: Map(4) {
          'accept' => { name: 'Accept', value: 'application/json' },
          'accept-encoding' => { name: 'Accept-Encoding', value: 'gzip,deflate' },
          'user-agent' => {
            name: 'User-Agent',
            value: 'azsdk-js-node/1.0.0-beta.1 core-rest-pipeline/1.9.0 Node/v16.15.1 OS/(x64-Darwin-21.5.0)'
          },
          'x-ms-client-request-id' => {
            name: 'x-ms-client-request-id',
            value: 'bbe96b86-0e5b-4817-b0e9-ecca29f5502a'
          }
        }
      },
      method: 'GET',
      timeout: 0,
      formData: undefined,
      disableKeepAlive: false,
      proxySettings: undefined,
      streamResponseStatusCodes: Set(0) {},
      withCredentials: false,
      abortSignal: undefined,
      tracingOptions: undefined,
      onUploadProgress: undefined,
      onDownloadProgress: undefined,
      requestId: 'bbe96b86-0e5b-4817-b0e9-ecca29f5502a',
      allowInsecureConnection: true,
      enableBrowserStreams: false
    },
    bodyAsText: ''
  },
  details: { body: undefined },
  rawTx: 'tx_+KoLAcC4pfijUQKhAT21xmmqI1dlBxO+8Zo0mbMsHoDpvFM4Govxqr9DlYp0kCsRbPJXCxtvhwqs7mDkZ0MDhkWq08owAILDUIQ7msoAuFz4WgsBwLhV+FMMAaEBPbXGaaojV2UHE77xmjSZsywegOm8Uzgai/Gqv0OVinShAU66rrKM0HKOLI1Jv/U7dNdEB3wWAV98Y1eRkF+yTpvlgicQhg8wRZFYAAAAgNJFoCI=',
  verifyTx: [AsyncFunction: verifyTx]
}
```

## Specifications

  - Node deployed at https://testnet.aeternity.io/
  - Node Version: 6.5.2

**Comment by hanssv** [comment]
412 is some caching stupidity, let me guess you are not using a simple node but something behind a loadbalance/cache?!
I see Cloudfront being mentioned in the log - I don't think this has anything to do with the core node?

**Comment by marc0olo** [comment]
cc @mmpetarpeshev @dincho

**Comment by nikita-fuchs** [comment]
Strongly recommend testing against non-cloud node.

**Comment by marc0olo** [comment]
> definitely recommend testing against non-cloud node.

sure that has been recommended since the beginning. nevertheless this is an issue and currently the reporting party isn't capable of setting up their own infrastructure (as discussed in the chat)

------------

@davidyuk can we replay this issue on testnet? does it always happen? can you verify with a local instance?

**Comment by nikita-fuchs** [comment]
> sure that has been recommended since the beginning. nevertheless this is an issue and currently the reporting party isn't capable of setting up their own infrastructure 

Don't we have `devmode` for this ?
besides that, _you_ could set up your own infrastructure or `devmode` and verify/falsify?
Shooting out transactions in a for-loop like that is _predestined_ to run into loadbalancer request errors as the syncing between the balanced nodes is just not as fast as all the SDK logic taking place there under the hood expects.

**Comment by marc0olo** [comment]
> Don't we have `devmode` for this ?

what should `devmode` have to do with this?! doesn't make sense to me

**Comment by nikita-fuchs** [comment]
It is easy and fast own infrastructure to test against. Wasn't that what they were lacking ? Simpler than syncing a node.

**Comment by marc0olo** [comment]
true, but devmode is not a requirement to do exactly this. of course it's good to not waste resources for mining 😅

**Comment by nikita-fuchs** [comment]
not a requirement, but the easies way I guess? 🏎

**Comment by davidyuk** [comment]
> can you verify with a local instance?

It is not reproducable locally 

Here is an updated reproduction that ignores 404 errors on transaction polling:

```js
import { Node, AeSdk, MemoryAccount, generateKeyPair, salt } from './es/index.mjs';

const account = new MemoryAccount({
  keypair: {
    publicKey: 'ak_2dATVcZ9KJU5a8hdsVtTv21pYiGWiPbmVcU1Pz72FFqpk9pSRR',
    secretKey: 'bf66e1c256931870908a649572ed0257876bb84e3cdf71efb12f56c7335fad54d5cf08400e988222f26eb4b02c8f89077457467211a6e6d955edb70749c6a33b'
  }
});
const sdk = new AeSdk({
  nodes: [{ name: 'testnet', instance: new Node('https://testnet.aeternity.io') }],
  compilerUrl: 'https://compiler.aepps.com',
});
const ga = new MemoryAccount({ keypair: generateKeyPair() });
await sdk.spend(1e16, await ga.address(), { onAccount: account });

const authContractSource = `contract BlindAuth =
  stateful entrypoint authorize(r: int) : bool =
    // r is a random number only used to make tx hashes unique
    switch(Auth.tx_hash)
      None          => abort("Not in Auth context")
      Some(tx_hash) => true
`;
await sdk.createGeneralizedAccount('authorize', authContractSource, [], { onAccount: ga });
await sdk.addAccount(new MemoryAccount({ gaId: await ga.address() }), { select: true });

const r = () => salt();
const { publicKey } = generateKeyPair();

async function robustPoll(txHash) {
  try {
    await sdk.poll(txHash);
  } catch (error) {
    if (error.message.includes('Transaction not found')) {
      console.log(error.message);
      return robustPoll(txHash);
    }
    throw error;
  }
}

for (let i = 0; i < 100; i++) {
  console.log(`spend ${i}`);
  const { hash } = await sdk.spend(10000, publicKey, {
    authData: {
      source: authContractSource,
      args: [r()]
    },
    waitMined: false,
  });
  await robustPoll(hash);
}
```
it fails with 412 on sending from 9th to 70th

**Comment by marc0olo** [comment]
> it fails with 412 on sending from 9th to 70th, but sometimes can fail on initial funding

what's your conclusion?

**Comment by davidyuk** [comment]
I still don't know how to handle 412 error

**Comment by davidyuk** [comment]
I'm still facing this issue using testnet.aeternity.io and Generalized Accounts
